### ISSUE TITLE
Error in distributed.py: Parameter object has no attribute "_execution_engine"

### ISSUE THREAD

**Issue by ghostcow** [NVIDIA/nv-wavenet#32]
When running `python distributed.py -c config.json` with default settings on a 2 V100 GPU machine, I receive the following error:

```
python distributed.py -c config.json
['train.py', '--config=config.json', '--rank=0', '--group_name=group_2018_05_30-220302']
['train.py', '--config=config.json', '--rank=1', '--group_name=group_2018_05_30-220302']
Initializing Distributed
/home/ubuntu/nv-wavenet/pytorch/wavenet.py:46: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  self.conv.weight, gain=torch.nn.init.calculate_gain(w_init_gain))
/home/ubuntu/nv-wavenet/pytorch/wavenet.py:46: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  self.conv.weight, gain=torch.nn.init.calculate_gain(w_init_gain))
output directory checkpoints
Epoch: 0
train.py:141: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  reduced_loss = reduce_tensor(loss.data, num_gpus)[0]
Traceback (most recent call last):
  File "train.py", line 193, in <module>
    train(num_gpus, args.rank, args.group_name, **train_config)
  File "train.py", line 144, in train
    loss.backward()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/ubuntu/nv-wavenet/pytorch/distributed.py", line 133, in allreduce_hook
    param._execution_engine.queue_callback(allreduce_params)
AttributeError: 'Parameter' object has no attribute '_execution_engine'
train.py:141: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  reduced_loss = reduce_tensor(loss.data, num_gpus)[0]
Traceback (most recent call last):
  File "train.py", line 193, in <module>
    train(num_gpus, args.rank, args.group_name, **train_config)
  File "train.py", line 144, in train
    loss.backward()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/ubuntu/nv-wavenet/pytorch/distributed.py", line 133, in allreduce_hook
    param._execution_engine.queue_callback(allreduce_params)
AttributeError: 'Parameter' object has no attribute '_execution_engine'
```

When poking around online, I found this issue which looks similar: https://github.com/NVIDIA/sentiment-discovery/issues/16

The issue implies that the the code expects a Variable class, but what it gets is a torch.cuda.FloatTensor in this case.

Don't really know how to fix this, apologies.

**Comment by sdorminey** [comment]
You were on the right track with NVIDIA/sentiment-discovery. It seems to be a breaking change in PyTorch.

As a fix:
1. Add `from torch.autograd import Variable` at the top.
2. Replace line 133 with `Variable._execution_engine.queue_callback(allreduce_params)`

**Comment by ghostcow** [comment]
Thanks @sdorminey I'll try the fix out
The only thing is, isn't Variable deprecated? Have they placed this functionality somewhere else in torch 0.4?
